### ISSUE TITLE
No tips about GnuPG

### ISSUE THREAD

**Issue by chtfn** [lochland/metametadata#2]
There should be something about Gnu Privacy Guard or Pretty Good Privacy in the "Encrypt your email" section of [protect.md](https://github.com/lochland/metametadata/blob/master/protect.md), or at least a link to a good step-by-step tutorial.

**Comment by lochland** [comment]
This is on tomorrow's agenda.

**Comment by lochland** [comment]
All done, but feel free to review and add, @chtfn.
