### ISSUE TITLE
https

### ISSUE THREAD

**Issue by chtfn** [lochland/metametadata#4]
The website should offer HTTPS access for obvious reasons :)

**Comment by lochland** [comment]
I've set up a Cloudflare account, which provides Universal SSL for free. The changes take about a day to propogate, so I won't close this issue until I can confirm on a couple of machines that https is working.

**Comment by chtfn** [comment]
Still can't see it, just so you know:
![arbeitsflache 1_303](https://cloud.githubusercontent.com/assets/1747497/6880955/ccce6ce8-d594-11e4-8b1d-6fb04f2fbf09.png)

**Comment by lochland** [comment]
I've still got some setup to do... :)

**Comment by lochland** [comment]
There are some issues with Dreamhost. I'm working on them.

**Comment by lochland** [comment]
Still working on them. Should be resolved very soon.

**Comment by lochland** [comment]
Tested, complete.

**Comment by chtfn** [comment]
Thanks :)
