### ISSUE TITLE
License for content

### ISSUE THREAD

**Issue by lochland** [lochland/metametadata#5]
I'd prefer to go with a [public domain](http://creativecommons.org/about/cc0) license, but I'd be also happy with an [Attribution](http://creativecommons.org/licenses/by/4.0/) license. Anything more restrictive will be counterproductive.

There also needs to be clear delineation between what is captured under the copyright of this site, and what doesn't belong to us (quotes, etc.).

**Comment by chtfn** [comment]
I guess a simple statement like "The content of this website, except when specifically linked to an external reference, is licensed under xxx" would do, right?

**Comment by lochland** [comment]
Something like the copyright notice on [my site](http://loch.land/about/) should suffice, I would think.

But which license?

**Comment by chtfn** [comment]
OK. I reckon public domain if just are publishing basic info like at the moment, but attribution if we produce posts that involve a bit of opinion in the future (could also be more suited to potential future contributors).

**Comment by lochland** [comment]
OK.

**Comment by lochland** [comment]
Public domain. https://metametadata.org/about/

**Comment by chtfn** [comment]
Goodo.
